add GoogleDrive support
Updated the workflow to install gdown and enhanced the firmware download logic to handle Google Drive links.

diff --git a/.github/workflows/withoutsafedisk.yml b/.github/workflows/withoutsafedisk.yml
--- a/.github/workflows/withoutsafedisk.yml
+++ b/.github/workflows/withoutsafedisk.yml
@@ -38,7 +38,7 @@ jobs:
       - name: Install Python Dependencies
         run: |
           python3 -m pip install --upgrade pip
-          python3 -m pip install protobuf==3.20.3
+          python3 -m pip install protobuf==3.20.3 gdown
           
           
       - name: Install Python Dependencies
@@ -56,13 +56,23 @@ jobs:
       - name: Download Firmware
         id: download
         run: |
-          wget -q -O firmware.zip "${{ steps.prep.outputs.url }}"
-          if [ -f firmware.zip ]; then
-            echo "Download Successful."
-            du -h firmware.zip
+         LINK="${{ steps.prep.outputs.url }}"
+         LINK="${{ steps.prep.outputs.url }}"
+
+         if [[ "$LINK" == *"drive.google.com"* ]]; then
+          echo "Google Drive detected."
+          gdown --fuzzy "$LINK" -O firmware.zip
           else
-            echo "Download Failed."
-            exit 1
+          echo "Direct download detected."
+          wget --progress=bar:force:noscroll -O firmware.zip "$LINK"
+          fi
+
+          if [[ -s firmware.zip ]]; then
+          echo "Download Successful."
+          ls -lh firmware.zip
+          else
+          echo "Download Failed."
+          exit 1
           fi
       - name: Make all scripts executable
         run: |
